name: mv_joint
model:
  num_views: 6
  pretrained: lambdalabs/sd-image-variations-diffusers
  pretrained_unet: ../autodl-tmp/outputs/mv_image_finetune/unet-10000
  unet:
    target: models.model.UNetMV2DConditionModel
    params:
      camera_embedding_type: e_de_da_sincos
      projection_class_embeddings_input_dim: 10
      num_views: 6
      sample_size: 32
      zero_init_conv_in: false
      zero_init_camera_projection: false
      cd_attention_last: false
      cd_attention_mid: true
      multiview_attention: true
      sparse_mv_attention: false
      mvcd_attention: false
datasets:
  train_dataset:
    target: datasets.MVImageDepthDataset
    params:
      root: ../autodl-tmp/new_renderings
      split: train
      bg_color: three_choices
  val_dataset:
    target: datasets.MVImageDepthDataset
    params:
      root: ../autodl-tmp/new_renderings
      split: val
      bg_color: white
  train_val_dataset:
    target: datasets.MVImageDepthDataset
    params:
      root: ../autodl-tmp/new_renderings
      split: train_val
      bg_color: three_choices
training:
  resume_from_checkpoint: null
  trainable_modules: ['joint_mid']
  output_dir: ../autodl-tmp/outputs/mv_joint
  mixed_precision: fp16
  use_ema: true
  log_with: tensorboard
  batch_size: 8
  max_train_steps: 20000
  gradient_accumulation_steps: 16
  gradient_checkpointing: true
  checkpointing_steps: 1000
  learning_rate: 5e-5
  optimizer:
    target: torch.optim.AdamW
    params:
      betas: [0.9, 0.999]
      weight_decay: 1e-2
      eps: 1e-8
  lr_scheduler:
    target: diffusers.optimization.get_scheduler
    params:
      name: constant_with_warmup
      num_warmup_steps: 100
  condition_drop_rate: 0.05
  condition_drop_type: drop_as_a_whole
  snr_gamma: 5.0
  max_grad_norm: 1.0
  validation_steps: 1000
  validation_sanity_check: true
      
